### ISSUE TITLE
Wnioski z lab2

### ISSUE THREAD

**Issue by andrzejwp** [hizonglol/pamsi-2015#1]
dotyczy 577daeab0e3e66530ba7e033e7a72ad7b70ebffc

brak wniosków z obliczeń. Czy Pańskie implementacje działają zgodnie z założeniami teoretycznymi, czy nie?

**Comment by hizonglol** [comment]
Już poprawiłem. Wnioski dodane. Do zamknięcia czy jeszcze jakiś problem?
